### ISSUE TITLE
[REMOTO] Full-Stack Engineer

### ISSUE THREAD

**Issue by rodrigooler** [brokerse/jobs#1]
# Full-Stack Engineer

# Descrição da vaga
Estamos buscando Full-Stack Engineers para desenvolver e polir nossa ferramenta. Candidatos devem ter conhecimento pleno de Node, JavaScript / Typescript, React, GraphQL, Programação Funcional e ter experiência com TDD.

Trabalho 100% remoto, com possibilidade de eventuais encontros para coordenação e acompanhamento.

# Local
100% Remoto.

# Requisitos

## Obrigatórios:
- [ ] 2 anos de experiência trabalhando com Javascript / Typescript;
- [ ] Costume de sempre documentar e coordenar trabalho tendo em mente que múltiplos engenheiros remotos estarão trabalhando juntos em uma mesma empreitada;
- [ ] Programação Funcional;
- [ ] Git & Github
- [ ] Inglês básico;

### Front-end
- [ ] HTML5;
- [ ] CSS
- [ ] Experiência em desenvolver componentes modulares e reutilizáveis;
- [ ] Apollo GraphQL;
- [ ] React (100% Hooks, zero classes);
- [ ] Styled Components;

### Back-end
- [ ] NodeJS;
- [ ] MongoDB;
- [ ] Mongoose; 
- [ ] Deploy (Heroku, Zeit/NOW ou AWS;

## Desejáveis (NÃO OBRIGATÓRIO):
- [ ] React Native;
- [ ] React Native Web;
- [ ] Experiência trabalhando de forma remota
- [ ] Experiência prévia com linguagens funcionais como Elixir, OCaml, ReasonML ou Haskell;

# Contratação
Contrato de Prestação de Serviço com Empresa Nacional, CNPJ necessário

# Como se candidatar
Enviar e-mail para flavio.brognara@clubinvest.io e rodrigo.oler@clubinvest.io com CV + Linkedin + Github + Enviar pretenção salarial

# Challenge

https://github.com/brokerse/jobs/tree/master/challenges/sharegram

**Comment by soutot** [comment]
- [ ] 2 anos de experiência trabalhando com Javascript / Typescript;
- [ ] Javascript / Typescript;
Ficou redundante

**Comment by rodrigooler** [comment]
@soutot vlw, vou ajustar!

**Comment by bonejah** [comment]
Aceita freelance ou part time?

**Comment by rodrigooler** [comment]
@bonejah por enquanto estamos procurando para full-time, mas nos envie um e-mail com seus dados e pretenção salarial para avaliarmos futuras vagas.
